### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by LLLowen** [Botmock/botmock-rasa-export#21] opened 2019-12-25 07:50 UTC
i do it as you say ,but somthing was wrong.  
![image](https://user-images.githubusercontent.com/47649960/71437835-40f50600-272e-11ea-9745-0ffde91a7f2e.png)

**Comment by nonnontrivial** [comment] 2020-01-06 16:53
@LLLowen thank you for opening this issue. We have pushed a fix. Can you `git pull origin master` and confirm that the issue is resolved?

**Closed** 2020-02-12 15:02 UTC
Labels: bug
